services:
  db:
    image: postgres:latest 
    container_name: sustainable_campus_db
    restart: unless-stopped 
    environment:
      POSTGRES_USER: sustainable_campus_user
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: sustainable_campus
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck: #
      test: ["CMD-SHELL", "pg_isready -U sustainable_campus_user -d sustainable_campus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s 

  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile 
    container_name: sustainable_campus_backend 
    restart: unless-stopped 
    env_file:
      - ./backend/.env 
    depends_on:
      db: 
        condition: service_healthy
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      NODE_ENV: production 

  frontend:
    build: ./frontend
    container_name: sustainable_campus_frontend 
    restart: unless-stopped 
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend 
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

volumes:
  postgres_data: