services:
  postgres_db:
    image: postgres:latest
    container_name: sustainableCampus_postgres 
    environment:
      POSTGRES_USER: ${DB_USERNAME} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE} 
    ports:
      - "${DB_PORT:-5432}:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    restart: unless-stopped

volumes:
  postgres_data: 